version: '3'

volumes:
  db-data:

services:
  db:
    image: library/postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash entry_point.sh
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/serurepo
