name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        docker-compose build
        docker-compose run web yarn install --check-files
        docker-compose run web yarn upgrade

    - name: Rubocop
      run: docker-compose run web bundle exec rubocop

    - name: Slim Lint
      run: docker-compose run web bundle exec slim-lint app/views
      
    - name: ESLint
      run: docker-compose run web yarn eslint
      
    - name: Prettier
      run: docker-compose run web yarn prettier
