name: Move new issues into serurepo
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: 開発
          column: いつかやる
          repo-token: ${{ secrets.GH_TOKEN }}
          
