name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker
      shell: bash
      run: |
        docker-compose build
        docker-compose run web yarn install --check-files
        docker-compose run web yarn upgrade
      
    - name: Run tests
      run: docker-compose run web bundle exec rspec

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
  
