name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker
      shell: bash
      run: |
        docker-compose build
        docker-compose run web yarn install --check-files
        docker-compose run web yarn upgrade
        docker-compose run web yarn build
        docker-compose run web echo ${{ secrets.RAILS_MASTER_KEY }} >> config/master.key
        docker-compose run web bin/rails db:create
      
    - name: Run tests
      run: docker-compose run web bundle exec rspec
